function make_setup()
    home_dir='/home/momoko/Documents/research_programs/icpr2020/sfm_spherical_integration_real_environment/';
    setup = struct( ...
        'color_lsm', 2, ... % Color plane used for light-section method
        'csv_dir', [home_dir, 'csv/'], ...
        'panhead_calib_dir', [home_dir, 'images/calibration_panhead2cam/'], ...
        'mask_dir', [home_dir, '/images/mask/'], ...
        'img_laser_dir', [home_dir, 'images/laser_detection/'],  ...
        'img_no_laser_dir', [home_dir, 'images/sfm_input/'] ...
    );
    save mat/setup.mat setup
end